language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/activerecord_3.1.gemfile
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.0.gemfile
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/activerecord_4.0.gemfile
